name: build docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DOCKER_REPO: jonoh/plex

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build only
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          BUILD_OUTPUT: load
        run: ./build.sh

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          IMAGE_NAME: ${{ env.DOCKER_REPO }}
          BUILD_OUTPUT: push
        run: ./build.sh

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REPO }}
